version: "3.8"

services:
  app:
    container_name: administrator-console-ui
    image: administrator-console-ui
    build:
      context: .
      target: development
    volumes:
      - ./src:/app/src
    ports:
      - 3008:3008
